default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Settings.db.username %>
  password: <%= Settings.db.password %>
  host: <%= Settings.db.host %>
  port: <%= Settings.db.port %>
  database: <%= Settings.db.name %>
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
